// zipFolder.ts

import * as fs from 'fs';
import * as path from 'path';
import Zip from 'node-zip';

// Generated by ChatGPT using the gpt-4 model

/**
 * Zips all files in a folder using the node-zip package synchronously.
 * @param sourceFolder - The path to the folder containing the files to be zipped.
 * @param outputZipFile - The path where the output zip file should be created.
 */
export function zipFiles(sourceFolder: string, outputZipFile: string): void {
  const zip = new Zip();

  try {
    const files = fs.readdirSync(sourceFolder);

    files.forEach((file) => {
      const filePath = path.join(sourceFolder, file);
      const fileContent = fs.readFileSync(filePath);
      zip.file(file, fileContent);
    });

    const data = zip.generate({ base64: false, compression: 'DEFLATE' });
    fs.writeFileSync(outputZipFile, data, 'binary');
  } catch (error) {
    throw new Error(`Error zipping files: ${error}`);
  }
}
