action_id: trunk-upgrade-available
date: 2023-04-01 08:10:43
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\n\x1b[0m"
  err: ""
timestamp: 1680336643
full_timestamp:
  nanos: 7102000
  seconds: 1680336643
trunk_version: 1.6.1
